import {readFile,mkdir,writeFile,cp,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {tools,guides} from './content.mjs';
import {escapeHtml as e} from '../assets/core.mjs';
const config=JSON.parse(await readFile(new URL('../config.json',import.meta.url),'utf8'));
const origin=new URL(config.origin).origin;
if(config.ads.enabled) throw new Error('Publicité verrouillée : valider AdSense et une CMP certifiée avant toute intégration.');
const out=new URL('../dist/',import.meta.url);await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
await cp(new URL('../assets/',import.meta.url),new URL('assets/',out),{recursive:true});
const favicon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="9" fill="#174cce"/><path d="M12 8h12l5 5v20H12z" fill="white"/><path d="M17 18h7M17 23h7M17 28h4" stroke="#174cce" stroke-width="2"/><path d="M24 8v6h5" fill="#f7c948"/></svg>';
await writeFile(new URL('favicon.svg',out),favicon);
const cards=(items)=>`<div class="grid">${items.map((t,i)=>`<a class="card" href="/${t.slug}/"><span class="number">${String(i+1).padStart(2,'0')} / ${t.tag}</span><h2>${t.name}</h2><p>${t.short}</p><span class="action">Créer ma fiche</span></a>`).join('')}</div>`;
const related=(ids)=>`<section class="related no-print"><h2>D’autres fiches utiles</h2>${cards(ids.map(id=>tools.find(t=>t.id===id)))}</section>`;
function page({path,title,description,body,schema=[],tool='',noindex=false}){
 const ld=[{'@context':'https://schema.org','@type':'WebSite',name:'Mes Fiches Assmat',url:origin+'/',inLanguage:'fr-FR'},...schema];
 const json=JSON.stringify(ld).replaceAll('<','\\u003c');
 return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | Mes Fiches Assmat</title><meta name="description" content="${e(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow'}"><link rel="canonical" href="${origin}${path}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="theme-color" content="#174cce"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${origin}${path}"><meta property="og:locale" content="fr_FR"><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${json}</script>${tool?'<script type="module" src="/assets/app.mjs"></script>':''}</head><body${tool?` data-tool="${tool}"`:''}><a class="skip" href="#main">Aller au contenu</a><header><nav class="nav" aria-label="Navigation principale"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">≡</span>Mes Fiches Assmat</a><div class="nav-links"><a href="/#outils">Les outils</a><a href="/guides/">Les guides</a></div></nav></header><main id="main">${body}</main><footer><div class="footer-inner"><p><strong>Mes Fiches Assmat</strong><br>Des fiches pour le quotidien de l’accueil.</p><div class="footer-links"><a href="/a-propos/">À propos</a><a href="/confidentialite/">Confidentialité</a><a href="/mentions-legales/">Mentions légales</a><a href="/contact/">Contact</a></div></div></footer></body></html>`;
}
const pages=[];
const hashes=new Set();
async function save(path,html,index=true){const file=path==='/'?'index.html':path==='404'?'404.html':path.slice(1)+'index.html';await mkdir(new URL(file.replace(/[^/]+$/,''),out),{recursive:true});await writeFile(new URL(file,out),html);for(const match of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/g))hashes.add(`'sha256-${createHash('sha256').update(match[1]).digest('base64')}'`);if(index)pages.push(path);}
const breadcrumbs=(name,guide=false)=>`<p class="breadcrumb"><a href="/">Accueil</a> / ${guide?'<a href="/guides/">Guides</a> / ':''}${e(name)}</p>`;
const guideCards=`<div class="grid">${guides.map((g,i)=>`<a class="card guide-card" href="/guides/${g.slug}/"><span class="number">GUIDE ${i+1}</span><h2>${g.title}</h2><p>${g.description}</p><span class="action">Lire le guide</span></a>`).join('')}</div>`;
await save('/',page({path:'/',title:'Fiches assistante maternelle gratuites à imprimer',description:'Six outils gratuits pour les assistantes maternelles : feuille de présence, transmissions, planning, coupons d’horaires, menus et étiquettes. Sans compte.',body:`<div class="eyebrow">LE QUOTIDIEN DE L’ACCUEIL, SUR PAPIER</div><h1>Votre prochaine fiche,<br>prête à imprimer.</h1><p class="intro">Choisissez un modèle, personnalisez-le et imprimez. Des outils gratuits pour les assistantes et assistants maternels, sans inscription.</p><div class="promise"><span>Gratuit</span><span>Sans compte</span><span>Saisie dans votre navigateur</span><span>Papier A4 ou PDF</span></div><section id="outils" aria-label="Les six outils">${cards(tools)}</section><div class="home-note"><strong>Des fiches utiles. Vos informations restent chez vous.</strong><p>Les outils ne transmettent pas les champs saisis. Ils ne les conservent pas après fermeture de la page. Enregistrez votre PDF avant de quitter.</p></div><section><div class="section-head"><h2>Bien utiliser vos fiches</h2><a href="/guides/">Tous les guides</a></div>${guideCards}</section><section class="article"><h2>Les bons documents pour le bon moment</h2><p>Le planning prépare les horaires d’une semaine. La feuille de présence suit les arrivées et départs réels du mois. La fiche de transmission partage les moments de la journée. Les coupons, menus et étiquettes complètent l’organisation sans imposer un logiciel de gestion.</p><p>Chaque outil possède sa propre page, ses explications et un aperçu imprimable. Les formulaires sont facultatifs : vous pouvez créer une fiche vierge pour la remplir au stylo. Sur ordinateur comme sur téléphone, le bouton d’impression permet d’utiliser une imprimante ou d’enregistrer un PDF avec les options du navigateur.</p><p>Ces modèles sont des aides d’organisation. Ils ne calculent pas une rémunération et ne remplacent pas les contrats, les démarches Pajemploi ou les documents obligatoires. Pour une question réglementaire, consultez <a href="https://www.service-public.gouv.fr/particuliers/vosdroits/N20383" rel="noopener">Service Public</a> ou votre relais petite enfance.</p></section>`}));
function field(name,label,type='text',extra='',help=''){return `<label class="field" for="${name}">${label}<input id="${name}" name="${name}" type="${type}" ${extra}>${help?`<small>${help}</small>`:''}</label>`;}
function textarea(name,label){return `<label class="field" for="${name}">${label}<textarea id="${name}" name="${name}" maxlength="600" rows="3"></textarea></label>`;}
function controls(t){
 let fields='';
 if(t.id==='presence') fields=field('month','Mois','month','min="1900-01" max="2100-12" required')+field('child','Prénom ou initiales','text','maxlength="50" autocomplete="off"')+field('caregiver','Assistant(e) maternel(le)','text','maxlength="70" autocomplete="off"')+'<p class="tiny">Complétez les horaires dans l’aperçu. Une case vide reste vide à l’impression.</p>';
 if(['planning','coupons'].includes(t.id))fields=field('week','Une date de la semaine','date','min="1900-01-01" max="2100-12-31" required')+field('child','Prénom ou initiales','text','maxlength="50" autocomplete="off"')+field('caregiver','Assistant(e) maternel(le)','text','maxlength="70" autocomplete="off"');
 if(t.id==='coupons')fields+='<label class="field" for="copies">Exemplaires identiques<select id="copies" name="copies"><option value="1">1 coupon</option><option value="2">2 coupons</option><option value="4" selected>4 coupons</option></select></label><p class="tiny">Saisissez les horaires sur le premier coupon. Les copies se mettent à jour.</p>';
 if(t.id==='transmission')fields=field('date','Date de la journée','date','min="1900-01-01" max="2100-12-31" required')+field('child','Prénom ou initiales','text','maxlength="50" autocomplete="off"')+field('caregiver','Assistant(e) maternel(le)','text','maxlength="70" autocomplete="off"')+field('arrival','Arrivée','time')+field('departure','Départ','time')+textarea('meals','Repas et goûter')+textarea('sleep','Sieste et repos')+textarea('changes','Changes')+textarea('activity','Activité et petit moment du jour')+textarea('message','Message aux parents');
 if(t.id==='menus')fields=field('week','Une date de la semaine','date','min="1900-01-01" max="2100-12-31" required')+field('heading','Titre ou lieu d’accueil','text','maxlength="70" autocomplete="off"')+'<p class="tiny">Saisissez les repas dans les cases de l’aperçu.</p>';
 if(t.id==='etiquettes')fields=field('child','Prénom, initiales ou mot','text','maxlength="35" autocomplete="off"')+field('subtitle','Seconde ligne (facultative)','text','maxlength="45" autocomplete="off"')+'<p class="tiny">24 étiquettes identiques. Format générique 60 × 30 mm à découper. Impression A4, échelle 100 %.</p>';
 return `<form class="controls" id="controls"><h2>Personnaliser la fiche</h2>${fields}<button type="button" class="button" id="print">Imprimer / PDF</button>${t.id==='presence'?'<button type="button" class="button secondary" id="csv">Exporter en CSV</button>':''}<button type="button" class="button quiet" id="reset">Effacer la saisie</button><p class="status" id="status" role="status" aria-live="polite"></p><p class="tiny">Aucune sauvegarde automatique. Enregistrez le document avant de fermer cette page.</p><a class="tiny" href="/guides/imprimer-fiches-pdf-telephone/">Comment enregistrer un PDF ?</a></form>`;
}
function article(sections){return sections.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join('');}
for(const t of tools){
 const path=`/${t.slug}/`;
 const schema=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Accueil',item:origin+'/'},{'@type':'ListItem',position:2,name:t.name,item:origin+path}]},{'@context':'https://schema.org','@type':'WebApplication',name:t.title,url:origin+path,applicationCategory:'UtilitiesApplication',operatingSystem:'Tout navigateur moderne',browserRequirements:'JavaScript pour la personnalisation',inLanguage:'fr-FR',offers:{'@type':'Offer',price:'0',priceCurrency:'EUR'}}];
 await save(path,page({path,title:t.title,description:t.description,tool:t.id,schema,body:`${breadcrumbs(t.name)}<div class="tool-head"><div class="eyebrow">${t.tag} <span class="badge">GRATUIT</span></div><h1>${t.title}</h1><p class="intro">${t.intro}</p></div><noscript><p class="notice">Activez JavaScript pour personnaliser cette fiche. Les explications restent accessibles ci-dessous.</p></noscript><div class="workspace">${controls(t)}<section class="preview-wrap" aria-label="Aperçu de la fiche"><div class="preview-toolbar"><strong>Aperçu du document</strong><span>A4 · sans les menus du site</span></div><div class="sheet" id="sheet"><h2>${t.name}</h2><p>Le document personnalisé apparaît ici lorsque JavaScript est activé.</p></div></section></div><section class="article">${article(t.sections)}<h2>Questions fréquentes</h2>${t.faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}<h2>Pour les démarches officielles</h2><p>Ces modèles d’organisation ne remplacent pas les documents obligatoires. Pour les questions de contrat, de rémunération ou de déclaration, consultez <a href="https://www.service-public.gouv.fr/particuliers/vosdroits/N20383" rel="noopener">Service Public</a>, <a href="https://www.pajemploi.urssaf.fr/" rel="noopener">Pajemploi</a> ou votre relais petite enfance.</p></section>${related(tools.filter(x=>x.id!==t.id).slice(0,3).map(x=>x.id))}`}));
}
await save('/guides/',page({path:'/guides/',title:'Guides pour organiser et imprimer vos fiches',description:'Choisissez la bonne fiche, organisez vos documents d’accueil et enregistrez vos modèles en PDF sur téléphone ou ordinateur.',body:`${breadcrumbs('Guides')}<div class="eyebrow">LES REPÈRES PRATIQUES</div><h1>Des fiches bien choisies,<br>et bien utilisées.</h1><p class="intro">Trois guides pour préparer vos documents, distinguer leurs usages et obtenir une impression lisible.</p>${guideCards}`}));
for(const g of guides){const path=`/guides/${g.slug}/`;await save(path,page({path,title:g.title,description:g.description,body:`${breadcrumbs(g.title,true)}<div class="eyebrow">GUIDE PRATIQUE</div><h1>${g.title}</h1><p class="intro">${g.description}</p><article class="article">${article(g.sections)}<p class="tiny">Publié le 8 octobre 2026. Rédaction : Mes Fiches Assmat.</p></article>${related(g.related)}`,schema:[{'@context':'https://schema.org','@type':'Article',headline:g.title,description:g.description,datePublished:config.release,dateModified:config.release,inLanguage:'fr-FR',author:{'@type':'Organization',name:'Mes Fiches Assmat',url:origin+'/a-propos/'},mainEntityOfPage:origin+path}]}));}
const email=config.editor.email;
const contact=email?`<p>Vous pouvez écrire à <a href="mailto:${e(email)}">${e(email)}</a>.</p>`:`<p>Pour signaler un problème technique ou proposer une amélioration, ouvrez un ticket dans <a href="https://github.com/dev-nicolas-gerard/git_playground/issues">le dépôt du projet</a>. Un compte GitHub est nécessaire. Les tickets sont publics : n’y joignez ni nom d’enfant, ni fiche remplie, ni coordonnées de famille.</p>`;
const legalReady=Boolean(config.editor.name&&config.editor.email&&config.editor.address);
const infos=[
 ['a-propos','À propos de Mes Fiches Assmat','La méthode et les limites des modèles gratuits de Mes Fiches Assmat.',`<h2>Des outils d’organisation pour les adultes</h2><p>Mes Fiches Assmat s’adresse aux assistantes et assistants maternels ainsi qu’aux parents qui préparent les documents du quotidien. Le site propose six générateurs distincts, des explications et des modèles imprimables.</p><h2>Notre choix de conception</h2><p>Les fiches se personnalisent dans le navigateur, sans compte et sans envoyer les champs saisis. Le site privilégie les tâches concrètes : inscrire des horaires, structurer une transmission et produire un document lisible. Les textes et les mises en page sont propres au projet.</p><h2>Ce que nous vérifions</h2><p>Les durées d’accueil sont calculées en minutes à partir des créneaux saisis. Les dates mensuelles tiennent compte de la durée réelle du mois. Les pages prévoient une mise en forme A4 et une saisie accessible sur téléphone et ordinateur. Les modèles peuvent évoluer après les retours d’utilisation.</p><h2>Les limites</h2><p>Nous ne fournissons pas de calcul de paie, de contrat, de conseil juridique, médical ou nutritionnel. Le site est indépendant de Pajemploi, de la Caf et des administrations. Aucun agrément ou validation officielle des modèles n’est revendiqué.</p><h2>Financement</h2><p>Le site est actuellement gratuit et ne diffuse aucune publicité. Un financement publicitaire pourra être mis en place après validation du compte éditeur et des règles de consentement. Les champs remplis dans les fiches ne seront pas utilisés pour cibler des annonces.</p>`],
 ['confidentialite','Confidentialité et données saisies','Découvrez comment sont traitées les informations de vos fiches : saisie locale, absence de sauvegarde et copies PDF.',`<h2>Les champs de vos fiches</h2><p>Les prénoms, horaires et textes saisis sont traités dans la page ouverte. L’outil ne les transmet pas à un serveur, ne les place pas dans l’adresse de la page et ne les sauvegarde pas dans le stockage du navigateur. Fermer ou recharger la page efface la saisie.</p><h2>Les documents que vous enregistrez</h2><p>Le PDF est produit par la fonction d’impression de votre appareil. Le CSV est généré localement. Une fois enregistrés ou partagés, ces fichiers sont gérés par votre appareil et les services que vous choisissez. Le site ne peut ni les récupérer ni les effacer.</p><h2>Hébergement et données techniques</h2><p>Cloudflare héberge les pages et peut traiter des données techniques nécessaires à la fourniture et à la sécurité du service, comme l’adresse IP et les informations de requête. Consultez la <a href="https://www.cloudflare.com/privacypolicy/">politique de confidentialité de Cloudflare</a>. Nous ne mettons actuellement en place aucun outil de mesure d’audience ni traceur publicitaire.</p><h2>Publicité et cookies</h2><p>Aucun script Google AdSense n’est chargé dans cette version. Aucune bannière de consentement publicitaire n’est donc affichée. Cette page sera mise à jour avant une activation des annonces et de leur plate-forme de consentement.</p><h2>Vos précautions</h2><p>Utilisez un prénom ou des initiales lorsque cela suffit. N’écrivez pas d’informations sur d’autres familles dans une fiche destinée à un parent. Protégez les PDF et les feuilles papier. Pour nous contacter, utilisez la page <a href="/contact/">Contact</a> sans nous envoyer de document rempli.</p><p class="tiny">Dernière mise à jour : 8 octobre 2026.</p>`],
 ['mentions-legales','Mentions légales','Informations sur l’édition et l’hébergement de Mes Fiches Assmat.',`${legalReady?`<h2>Éditeur</h2><p>${e(config.editor.name)}<br>${e(config.editor.address)}</p>${contact}`:'<h2>Version de lancement</h2><p>Les coordonnées légales complètes de l’éditeur sont en cours de finalisation. Cette page ne constitue pas une présentation complète des mentions requises pour un site monétisé. Aucune publicité n’est activée dans cette version.</p>'}<h2>Hébergement</h2><p>Cloudflare, Inc.<br>101 Townsend Street, San Francisco, CA 94107, États-Unis.<br><a href="https://www.cloudflare.com/">www.cloudflare.com</a></p><h2>Nature des documents</h2><p>Les générateurs proposent des modèles d’organisation. Ils ne remplacent pas les documents obligatoires, les contrats ou les déclarations. Les pages ne sont affiliées à aucune administration.</p><h2>Utilisation des modèles</h2><p>Vous pouvez imprimer et utiliser les fiches générées pour votre organisation personnelle ou professionnelle. La reproduction de l’ensemble du site ou de ses contenus éditoriaux sur un autre site nécessite l’accord de l’éditeur.</p><h2>Signaler une erreur</h2><p>Consultez la page <a href="/contact/">Contact</a>. Décrivez le problème sans transmettre les données d’un enfant ou d’une famille.</p>`],
 ['contact','Contact et signalement d’un problème','Signalez un problème ou proposez une amélioration sans envoyer de données personnelles.',`<h2>Un problème avec une fiche ?</h2>${contact}<h2>Les informations utiles pour reproduire une erreur</h2><p>Indiquez le nom de l’outil, votre navigateur, le type d’appareil et ce qui s’est passé. Si le problème concerne un horaire, utilisez un exemple fictif. Pour un problème d’impression, précisez le format de papier et le réglage d’échelle.</p><h2>Pas de documents remplis</h2><p>Nous n’avons pas besoin du prénom d’un enfant, des coordonnées d’une famille ou d’une fiche réelle pour comprendre une erreur. Une description et des exemples anonymes protègent les personnes concernées.</p>`]
];
for(const [slug,title,description,body] of infos){const path=`/${slug}/`;await save(path,page({path,title,description,body:`${breadcrumbs(title)}<h1>${title}</h1><article class="article">${body}</article>`,noindex:slug==='mentions-legales'&&!legalReady}),slug!=='mentions-legales'||legalReady);}
await save('404',page({path:'/404.html',title:'Page introuvable',description:'Cette page n’existe pas. Retrouvez les outils gratuits.',noindex:true,body:'<div class="eyebrow">PAGE INTROUVABLE</div><h1>Cette fiche n’est pas ici.</h1><p class="intro">Retrouvez les modèles disponibles sur la page d’accueil.</p><a href="/">Voir les outils</a>'}),false);
await writeFile(new URL('sitemap.xml',out),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(path=>`<url><loc>${origin}${path}</loc><lastmod>${config.release}</lastmod></url>`).join('')}</urlset>`);
await writeFile(new URL('robots.txt',out),`User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
// Allow only exact structured-data scripts and our own modules. Revalidate assets after each release.
await writeFile(new URL('_headers',out),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src 'self'; script-src 'self' ${[...hashes].join(' ')}; style-src 'self'; img-src 'self' data:; connect-src 'none'; font-src 'self'; object-src 'none'; frame-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'\n/assets/*\n  Cache-Control: public, max-age=0, must-revalidate\n`);
console.log(`Built ${pages.length} indexable pages. Origin: ${origin}. Ads disabled. No server functions.`);
