export const guides=[
 {slug:'trait-de-scie-et-chutes',title:'Trait de scie : compter la matière qui disparaît',description:'Une liste de pièces ne suffit pas : méthode de calcul, exemple chiffré et distinction entre sciure, réserve et chute réutilisable.',sections:[
 ['Pourquoi additionner les longueurs ne suffit pas','Une lame enlève de la matière. Deux pièces de 1 000 mm ne peuvent donc pas sortir d’une barre de 2 000 mm si une coupe de 3 mm doit les séparer. Une estimation qui ignore cette perte peut annoncer une barre de moins et vous laisser avec une dernière pièce trop courte. Débit Futé traite cette largeur comme un espace entre les pièces et compte aussi la coupe qui détache la dernière pièce de sa chute.'],
 ['La formule d’une barre','Pour n pièces, la place nécessaire avant la coupe finale est la somme des longueurs + (n − 1) × trait de scie. Cette valeur doit rester inférieure ou égale à la longueur utilisable de la barre. La longueur utilisable correspond à la longueur achetée moins la réserve totale aux extrémités. Une barre déjà à la longueur exacte d’une seule pièce ne nécessite pas de coupe de séparation dans ce modèle.'],
 ['Exemple : trois pièces de 600 mm','Dans une barre de 2 000 mm, trois pièces de 600 mm représentent 1 800 mm utiles. Avec une largeur de coupe de 3 mm, les deux séparations entre les pièces consomment 6 mm. Il reste 194 mm avant de détacher la dernière pièce. Cette dernière coupe consomme encore 3 mm : la chute récupérable mesure donc 191 mm. Le bilan est 1 800 + 9 + 191 = 2 000 mm. Si vous réservez en plus 20 mm aux extrémités, la chute finale passe à 171 mm.'],
 ['Mesurer plutôt que deviner','Saisissez la largeur effective de coupe de votre outil, qui peut différer de l’épaisseur du corps de la lame. Une méthode pratique consiste à mesurer la longueur d’un morceau, réaliser une coupe droite, puis mesurer les deux morceaux : la différence entre la longueur initiale et la somme des deux longueurs donne la matière enlevée. La précision des mesures limite celle du résultat. Une valeur arbitraire de 3 mm est fournie comme exemple, pas comme caractéristique universelle d’une scie.'],
 ['Réserve aux extrémités et petite fin de barre','Le champ « Réserve totale par barre » permet d’exclure du débit une longueur que vous souhaitez garder pour un défaut, une remise d’équerre ou une marge choisie. Une réserve de 20 mm signifie 20 mm au total, et non 20 mm de chaque côté. Le calcul n’impose pas la position de cette réserve. Si la fin restante est plus courte que la largeur de coupe, elle est comptée intégralement comme perte : la lame déborde alors au-delà de l’extrémité dans le modèle géométrique. Le schéma est une représentation de répartition, pas une procédure de sciage.'],
 ['Une chute n’est pas une perte définitive','Le résultat distingue trois postes : les longueurs des pièces, les pertes incluant les coupes et la réserve, et les chutes en bout de barre. Une chute de 191 mm peut servir à un autre projet ; elle ne suffit pas à fabriquer une pièce de 200 mm. Le pourcentage de matière utile exprime seulement la part des longueurs achetées qui devient les pièces demandées. Il ne mesure ni le coût total du chantier ni la possibilité réelle de réutiliser chaque chute.'],
 ['Ce que le modèle ne traite pas','Les coupes sont droites et les pièces ont la même section et le même matériau. Les angles d’onglet, le sens du fil, les défauts internes, les assemblages et les surlongueurs propres à votre projet ne sont pas déterminés automatiquement. Ajoutez les longueurs nécessaires avant de saisir la liste. Contrôlez les cotes sur place et suivez les instructions de votre outillage. Le site n’évalue pas la résistance d’un ouvrage et ne donne pas de dimensionnement structurel.']
 ]},
 {slug:'comparer-longueurs-et-prix',title:'Quelle longueur acheter ? Comparer les barres et le prix',description:'Un exemple de comparaison entre des barres de 2,40 m et de 3 m, avec les hypothèses, les coûts saisis et les limites du résultat.',sections:[
 ['Le prix au mètre ne raconte pas tout','La longueur la moins chère au mètre peut exiger davantage de barres entières pour votre liste de pièces. Inversement, une barre plus longue peut réduire le nombre d’unités achetées tout en coûtant plus cher au total. Comparez donc le nombre de barres, le total payé et les chutes après avoir réparti la même liste de pièces. Les coûts dans Débit Futé viennent exclusivement de vos saisies : le site ne lit aucun catalogue et ne présente pas de prix actuels de magasin.'],
 ['Un exemple avec des prix fictifs','Prenez quatre pièces de 800 mm et quatre pièces de 450 mm, soit 5 000 mm utiles. Fixez le trait de scie à 3 mm et la réserve à zéro. Avec des barres de 2 400 mm, il faut au moins trois barres : deux ne contiennent que 4 800 mm, avant même les coupes. Le calcul propose une répartition en trois barres. À un prix fictif de 8 € par barre, l’achat coûte 24 €.'],
 ['La même liste dans des barres de 3 000 mm','Deux barres de 3 000 mm peuvent contenir chacune deux pièces de 800 mm et deux pièces de 450 mm. Une barre contient ainsi 2 500 mm de pièces, trois coupes intermédiaires et une coupe finale, soit 12 mm de pertes de sciage et 488 mm de chute. Les deux barres coûtent 22 € si le prix fictif est de 11 € par barre. Dans cet exemple, la barre de 3 m coûte plus cher à l’unité mais la proposition complète coûte 2 € de moins.'],
 ['Faire votre propre comparaison','Saisissez vos pièces dans le formulaire, puis la longueur et le prix d’une première barre. Ouvrez la comparaison et indiquez une seconde longueur et son prix. Le calcul répartit séparément la même liste dans chaque format. Il compare deux achats homogènes : toutes les barres du premier scénario ont la première longueur, et toutes les barres du second ont la seconde longueur. Il ne mélange pas les deux formats pour construire un troisième achat.'],
 ['Comparer des matériaux réellement comparables','Utilisez des prix correspondant à la même essence ou matière, à la même section, au même état de surface et à une qualité adaptée à votre projet. Une plinthe différente, un tasseau raboté plutôt que brut ou un profilé d’une autre épaisseur ne constituent pas un simple changement de longueur. Le calcul ne vérifie pas ces caractéristiques. Si vos pièces ont plusieurs sections, établissez une liste et un calcul séparés pour chaque groupe.'],
 ['Les coûts à ajouter avant de décider','Les résultats affichés portent sur les barres au prix unitaire saisi. Ils excluent les frais de livraison, les accessoires, la découpe payante en magasin et les coûts de déplacement. Si une longueur de 3 m nécessite une livraison alors que 2,40 m peut être transporté autrement, ajoutez ce coût au scénario concerné. Vérifiez également le stock disponible et les conditions de vente. Le prix d’un lot doit être ramené au prix d’une barre avant la saisie ; si le magasin impose l’achat du lot complet, le calcul ne tient pas compte de cette contrainte.'],
 ['Une proposition, pas une preuve du meilleur achat possible','Le moteur essaie quatre répartitions rapides et retient une proposition utilisant le moins de barres parmi celles trouvées. Il ne recherche pas toutes les combinaisons possibles. Le résultat ne garantit donc pas le minimum mathématique pour une liste complexe. Pour un achat important, confrontez le plan aux contraintes réelles, envisagez d’autres longueurs et vérifiez les coupes avant de commander. Les économies de cet exemple ne constituent pas une promesse d’économies pour tous les projets.']
 ]},
 {slug:'preparer-liste-de-debit',title:'Préparer une liste de débit lisible pour l’atelier',description:'Passer des mesures à une liste de pièces nommées, conserver les unités et relire un plan de coupe avant l’achat.',sections:[
 ['Commencer par une liste de pièces finies','Une liste de débit décrit ce que vous souhaitez obtenir, avec une longueur, une quantité et un nom pour chaque groupe de pièces. Elle ne décrit pas seulement le total de bois nécessaire. Deux projets de 5 mètres linéaires peuvent demander des achats très différents si l’un contient dix petites pièces et l’autre deux pièces longues. Mesurez votre projet, puis définissez la longueur à découper en tenant compte des contraintes propres à l’assemblage. Le calculateur ne déduit pas ces contraintes à partir d’une photographie ou d’un plan.'],
 ['Choisir une unité unique','Débit Futé utilise le millimètre. Une longueur de 80 cm s’écrit 800 ; une barre de 2,40 m s’écrit 2400. Les valeurs décimales sont acceptées avec une virgule ou un point. Faites les conversions avant de remplir la liste et relisez particulièrement les grandes valeurs. Une erreur entre 80 et 800 ne peut pas être détectée par l’outil si les deux dimensions sont géométriquement possibles. La largeur de coupe et la réserve sont également exprimées en millimètres.'],
 ['Le format de saisie','Écrivez une ligne par groupe, par exemple « 800 x 4 : montant » puis « 450 x 4 : traverse ». Le nom après les deux-points est facultatif ; il sert à retrouver les pièces dans les barres et dans le fichier CSV. Sans quantité, une ligne correspond à une pièce. Le calcul accepte jusqu’à 200 pièces, toutes quantités confondues. Ce plafond maintient un calcul rapide dans le navigateur et limite les erreurs de quantité ; il n’est pas une invitation à découper toute une liste sans contrôle intermédiaire.'],
 ['Séparer les sections et les matières','Quatre montants en tasseau de 30 × 30 mm et quatre traverses en tasseau de 20 × 40 mm ne peuvent pas être répartis dans les mêmes barres. Créez deux plans distincts. Faites de même pour des matières, essences, finitions ou orientations du fil différentes. Le nom donné à la pièce est une étiquette ; il n’ajoute pas une règle de compatibilité au moteur. Toutes les pièces d’un calcul sont supposées interchangeables du point de vue de la section et du matériau.'],
 ['Relire la feuille avant d’acheter','Le résultat donne le nombre de barres, les pièces affectées à chacune, les pertes comptées et les chutes en bout. Les rectangles verts représentent les pièces et le fond beige représente la fin de barre. Les très petites pièces peuvent ne pas porter de cote à l’intérieur du rectangle ; leur longueur reste lisible dans la liste placée sous le schéma. Vérifiez que le nombre de pièces correspond à votre besoin et qu’aucune pièce ne requiert une orientation ou un défaut à éviter. Les cotes écrites priment sur une mesure prise sur le schéma.'],
 ['Garder un document de travail','Le bouton « Imprimer / PDF » ouvre la fonction d’impression du navigateur. Choisissez A4 et vérifiez l’aperçu avant impression. L’export CSV produit un fichier à séparateur point-virgule, avec une ligne par pièce. Vous pouvez l’ouvrir dans un tableur pour cocher votre progression ou ajouter une remarque. Le document doit rester lié au matériau et aux hypothèses choisis : notez-les séparément si plusieurs achats se ressemblent. Aucun historique n’est enregistré par le site ; sauvegardez votre fichier avant de quitter.'],
 ['Contrôler à l’atelier','La répartition n’est pas une instruction d’utilisation d’une scie. Elle ne définit pas le bridage, l’ordre sûr des opérations ou les protections à utiliser. Les procédures et les consignes du fabricant de l’outil restent nécessaires. Une mesure réelle peut aussi révéler une barre plus courte, une extrémité abîmée ou un défaut à exclure. Dans ce cas, corrigez les hypothèses et recalculez. Le temps consacré à cette vérification évite de traiter un écran comme une garantie que toutes les coupes pourront être réalisées dans les conditions du chantier.']
 ]}
];
